In [1]:
import tensorflow as tf
import numpy as np

tf.enable_eager_execution()

/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


[]


In [2]:
#Tensor example
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 5]))
print(tf.encode_base64("hello worlds"))
print(tf.square(2) + tf.square(3))
x = tf.matmul([[5]], [[2,3]])
print(x)

True


In [3]:
#Conversion tensor <-> ndarray
ndarray = np.ones([3, 3])
print(ndarray)
tensor = tf.multiply(ndarray, 4)
print(tensor)
print(np.add(tensor, 1))
print(tensor.numpy())

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
tf.Tensor(
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]], shape=(3, 3), dtype=float64)
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


In [4]:
x = tf.random_uniform([3, 3])
print("Is GPU available:"),
print(tf.test.is_gpu_available());

print("Where is x storage:"),
print(x.device);

Is GPU available:
True
Where is x storage:
/job:localhost/replica:0/task:0/device:CPU:0


In [7]:
def time_matmul(x):
    %timeit tf.matmul(x, x)
    
#Execute in CPU
print("Matmul in CPU")
with tf.device("CPU:0"):
    x = tf.random_uniform([1000,1000])
    assert x.device.endswith("CPU:0")
    time_matmul(x)

#Execute in GPU
print("Matmul in GPU")
with tf.device("GPU:0"):
    x = tf.random_uniform([1000, 1000])
    assert x.device.endswith("GPU:0")
    time_matmul(x)

Matmul in CPU
27.4 ms ± 299 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Matmul in GPU
987 µs ± 24.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
#Create source dataset
ds_tensors = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6])

import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
    f.write("""Line1
    Line2
    Line3
    """)

ds_file = tf.data.TextLineDataset(filename)

In [9]:
#Transform data
ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)
ds_file = ds_file.batch(2)

In [10]:
#Eager execution with Dataset
print('Elements  of ds_tensors:')
for x in ds_tensors:
    print(x)
    
print('\nElements in ds_file:')
for x in ds_file:
    print(x)

Elements  of ds_tensors:
tf.Tensor([4 1], shape=(2,), dtype=int32)
tf.Tensor([16 25], shape=(2,), dtype=int32)
tf.Tensor([36  9], shape=(2,), dtype=int32)

Elements in ds_file:
tf.Tensor([b'Line1' b'    Line2'], shape=(2,), dtype=string)
tf.Tensor([b'    Line3' b'    '], shape=(2,), dtype=string)
